services:
  app:
    restart: always
    image: ghcr.io/reloadlife/go.mamad.dev:master
    environment:
      - CERT=/cert.pem
      - KEY=/key.pem
    ports:
      - "${HTTP_PORT:-8080}:80",
    volumes:
      - ./cert.pem:/cert.pem
      - ./key.pem:/key.pem