name: Build and Push Docker Image

on:
  push:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@f3c664df7af409cb4873aa5068053ba9d61a57b6
        with:
          cosign-release: 'v1.13.1'

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: echo "${{ steps.meta.outputs.tags }}" | xargs -I {} cosign sign {}@${{ steps.build-and-push.outputs.digest }}

  deploy:
    needs:
      - build
    environment:
      name: Deploy on Prod
      url: https://go.mamad.dev
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: create deploy directory
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{secrets.SSH_KEY}}
          port: 22
          script: |
            mkdir -p ${{secrets.SSH_PATH}}

      - name: Copy compose.yml on server
        uses: garygrossgarten/github-action-scp@release
        with:
          privateKey: ${{secrets.SSH_KEY}}
          host: ${{ secrets.SSH_HOST }}
          username: root
          local: compose.yml
          remote: ${{secrets.SSH_PATH}}/compose.yml

      - name: deploy to production
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{secrets.SSH_KEY}}
          port: 22
          script: |
            echo "${{secrets.CERT}}" > ${{secrets.SSH_PATH}}/cert.pem
            echo "${{secrets.KEY}}" > ${{secrets.SSH_PATH}}/key.pem
            echo "HTTP_PORT=8654" > ${{secrets.SSH_PATH}}/.env
            docker login -u  ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ${{ env.REGISTRY }}
            docker compose -f ${{secrets.SSH_PATH}}/compose.yml pull
            docker compose -f ${{secrets.SSH_PATH}}/compose.yml down
            docker compose -f ${{secrets.SSH_PATH}}/compose.yml up -d --remove-orphans